swagger: '2.0'
info:
  title: SUPERSEDE ReleasePlanner. Wrapper of Valentin's Implementation
  version: "1.0.0"
# the domain of the service
host: localhost
#release-planner-ui-api.herokuapp.com
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /replan:
    post:
      summary: Generates a Planning Solution for a given Next Release Problem
      operationId: replan
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/NextReleaseProblem'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/PlanningSolution'
        400:
          description: Bad Request
        422:
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'
definitions:
  Skill:
    type: object
    properties:
      name:
        type: string
  Priority:
    type: object
    properties:
      level:
        type: integer
      score:
        type: integer
  Feature:
    type: object
    properties:
      name:
        type: string
      duration:
        type: number
        format: double
      priority:
        $ref: '#/definitions/Priority'
      required_skills:
        type: array
        items:
          $ref: '#/definitions/Skill'
      depends_on:
        type: array
        description: array of features
        items:
          $ref: '#/definitions/Feature'
  Resource:
    type: object
    properties:
      name:
        type: string
      availability:
        type: number
        format: double
      skills:
        type: array
        items:
          $ref: '#/definitions/Skill'
  NextReleaseProblem:
    type: object
    properties:
      nbWeeks:
        type: integer
      hoursPerWeek:
        type: number
        format: double
      features:
        type: array
        items:
          $ref: '#/definitions/Feature'
      resources:
        type: array
        items:
          $ref: '#/definitions/Resource'
  PlannedFeature:
    type: object
    properties:
      beginHour:
        type: number
        format: double
      endHour:
        type: number
        format: double
      resource:
        $ref: '#/definitions/Resource'
      feature:
        $ref: '#/definitions/Feature'
  PlanningSolution:
    type: object
    properties:
      jobs:
        type: array
        items:
          $ref: '#/definitions/PlannedFeature'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string